---
- hosts: ataulfo
  become: true
  vars:
    amostra: false
  tasks:
    - name: Instala apache2 no Debian
      apt:
        name: ['apache2','libapache2-mpm-itk', 'vim']
        state: present
        update_cache: yes
        cache_valid_time: 90
      when: ansible_distribution == 'Debian'

    - name: Cria usuario besta
      user:
        name: besta
        comment: Ozuario besta

    - name: copiando nossa pagina
      copy:
        src: files/index.html
        dest: /var/www/html/index.html
        owner: besta
        group: besta
        mode: 0640

    - name: Ajusta permissões no arquivo de sites
      lineinfile:
        path: /etc/apache2/sites-available/000-default.conf
        regexp: '^AssignUserId besta besta$'
        line: 'AssignUserId besta besta'
        insertafter: '^DocumentRoot.*'
      register: lineresult

    - name: amostra as coisa
      debug:
        msg: "{{ lineresult }}"
      when: amostra == true

    - name: reinicia apache2
      service:
        name: apache2
        state: restarted
      when: lineresult.changed == true